language: python
cache: pip
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'
install:
- pip install -r requirements_dev.txt
- pip install .
script:
- make lint test BIN=""
deploy:
  provider: pypi
  username: __token__
  password:
    secure: QaJXhn36l9olZ4wL+hzVxN7rnYPJPn4xlm1AnJulPCdD283E0SawIhzTSu94+4okaWr+tYGlubemmwwsTTonXsl1KyKVmnfsBUHu3otjHlH9t5aO1aLgTX5juXirIF62JyOg1tTxlFHg0Rc1s+fyq79u30703dCaNs40W2iYIVrRu6LwLdPAnnCP91CZs1Y/6GPmsf12oDj7b3cH0VgKofrLHaGCSTuWiPHRYgr9nEN0EEz67FEW0M2yluJRP8v5YR8ZrE5nDPCk5zZgdQ4SIUD8d6qRzH3rwpMljJP9IeMbqi20r13ziwxgJx5N2nNieCYedCTiOk4BmLXhyP4X5Fh5Klh/iMYEG/FkzoXmQLDu2DPpQXcY8VEjSRnOc9ixFO9iy0KZcdhb6bqQA3n9g9CDol1GmwP6yH4XvIivG5MrTjisKn4Lnl5/poXZasolonAaWrbbFkWGwkroxPb8tqUAj74kQ5p0qV31hmE+56oz5Levf38DmWl+Dud+Mk9rxnTFc0vrw+wapjMVtmYlam0j+BQ7+lQOjTB/zujy4ZXVpEJfdxV0OX9PB4JHhYl704Qc4VEaaIQKArVSU7sHEdDH8cXV4Hy7nxpGYDINmwv+jauusat6jLKlwexQPpKTalByCdszvSEGDby1DX5MSFXnXDVh0nOO+2EOh6gQ6qo=
  on:
    branch: master
    tags: true
